[project]
name = "chess-agent"
version = "0.1.0"
requires-python = ">= 3.13"
dependencies = [
    "langchain",
    "langgraph",
    "langchain-anthropic",
    "python-chess",
    "streamlit",
    "python-dotenv",
    "pytest",
    "langserve[all]",
    "fastapi",
    "uvicorn[standard]",
]

[project.scripts]
chess-agent = "agent.run:main"

[tool.uv.scripts]
serve = "uvicorn server:app --reload"

[tool.hatch.build.targets.wheel]
packages = ["agent"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
